language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - PYTHONPATH=. py.test --cov-report term-missing --cov wunderlist

after_success:
  - coveralls