language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - grunt build
  - "cd dist/workflow && PYTHONPATH=. py.test ../../tests --cov-report term-missing --cov wunderlist"

after_success:
  - coveralls